- id: thoth-pre-commit-hook
  name: Thoth Adviser
  description: "Manage your Python dependencies with Thoth"
  entry: thoth-advise
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: false
  verbose: true
  always_run: true
  pass_filenames: false
  files: ''
